### ISSUE TITLE
When can us read the peer reviewed paper? 

### ISSUE THREAD

**Issue by xujingmei111** [Siliegia/SIGMA#3]
I'm curious what magazine did you submit and what the comments you have recieved and When is it expected to be published?

**Comment by mariamircea** [comment]
Hi!
the paper is currently under revision in a journal. You can read about the method for now only in the preprint on bioRxiv: https://www.biorxiv.org/content/10.1101/2021.05.11.443685v1 

The moment it will be published in a peer-reviewed journal, I will update the Github readme file with a new link!
